def additoin(x, y):
    try:
        x = 10
        y = 20
        print("Addition:", x + b)
    except Exception as e:
        print('The operation failed. The error is : ',e.__class__)
    else:
        print("the operation is successful")



additoin(10, 20)